import './run.mjs';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import assert from 'node:assert/strict';
const dir = path.resolve('.sites-runtime/tests');
const output = ts.transpileModule(fs.readFileSync('lib/demo.ts','utf8'), {compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/'\.\/domain\/(model|actions|sets)'/g, "'./$1.js'");
fs.writeFileSync(`${dir}/demo.js`, output);
const {createDemo,loadDemo,saveDemo,resetDemo,DEMO_KEY}=await import(`${dir}/demo.js`);
const data=new Map([['private-account', 'untouched']]);
const storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};
let state=loadDemo(storage);
assert.equal(state.sessions.length,4);
assert.ok(state.sessions.every(s=>s.status==='complete'));
const routine=JSON.stringify(state.routines);
state=saveDemo(storage,state,{type:'start'});
let session=state.sessions.at(-1), exercise=session.exercises[0];
state=saveDemo(storage,state,{type:'addSet',sessionId:session.id,exerciseId:exercise.id,id:'demo-extra',setType:'additional'});
state=loadDemo(storage);
assert.equal(state.sessions.at(-1).exercises[0].sets.at(-1).id,'demo-extra');
state=saveDemo(storage,state,{type:'saveSet',sessionId:session.id,exerciseId:exercise.id,set:{id:'demo-extra',weight:40,reps:7,rir:2,savedAt:new Date().toISOString()}});
assert.equal(JSON.stringify(state.routines),routine);
const stale=state;
state=saveDemo(storage,state,{type:'finish',id:session.id});
assert.throws(()=>saveDemo(storage,stale,{type:'start'}),/otra pestaña/);
assert.equal(loadDemo(storage).sessions.at(-1).exercises[0].sets.at(-1).reps,7);
assert.equal(resetDemo(storage).sessions.length,4);
assert.equal(data.get('private-account'),'untouched');
assert.equal(data.size,2);
assert.notEqual(createDemo().routines[0].days[0].exercises[0].id,createDemo().routines[0].days[0].exercises[0].id);
data.set(DEMO_KEY,'broken');
assert.throws(()=>loadDemo(storage),/Restablecer demo/);
resetDemo(storage);
assert.equal(loadDemo(storage).sessions.length,4);
console.log('PASS: demo synthetic seed, save/reload, additional set, history, routine isolation, stale-tab rejection, reset, corrupt-data recovery.');
