import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';import assert from 'node:assert/strict';
const dir=path.resolve('.sites-runtime/tests');fs.mkdirSync(dir,{recursive:true});
for(const file of ['model','progression','actions']){const src=fs.readFileSync(`lib/domain/${file}.ts`,'utf8');const out=ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replaceAll("'./model'","'./model.js'").replaceAll("'./progression'","'./progression.js'");fs.writeFileSync(`${dir}/${file}.js`,out);}
const {initialState,uid}=await import(`${dir}/model.js`),{reduce}=await import(`${dir}/actions.js`),{recommend,records,epley}=await import(`${dir}/progression.js`);
let state=initialState();const r=structuredClone(state.routines[0]);r.id=uid();r.name='Rutina de prueba';r.status='draft';r.days.forEach(d=>{d.id=uid();d.exercises.forEach(e=>e.id=uid());});state=reduce(state,{type:'saveRoutine',routine:r});assert.equal(state.routines.length,2);state=reduce(state,{type:'activate',id:r.id});assert.equal(state.routines.filter(r=>r.status==='active').length,1);state=reduce(state,{type:'duplicate',id:r.id});assert.equal(state.routines.length,3);
state=reduce(state,{type:'start'});let active=state.sessions.find(s=>s.status==='active');assert.throws(()=>reduce(state,{type:'start'}));let eid=active.exercises[0].id;
for(let i=0;i<3;i++){state=reduce(state,{type:'saveSet',sessionId:active.id,exerciseId:eid,set:{id:uid(),weight:60,reps:8,rir:i===2?2:3,savedAt:new Date().toISOString()}});}const restored=JSON.parse(JSON.stringify(state));assert.equal(restored.sessions[0].exercises[0].sets.length,3);assert.ok(restored.sessions[0].restUntil);state=reduce(restored,{type:'finish',id:active.id});assert.equal(state.routines.find(x=>x.id===r.id).nextDay,1);assert.equal(recommend(r.days[0].exercises[0],state.sessions).weight,62.5);assert.equal(records(state.sessions)[0].weight,60);assert.equal(epley(60,8),76);
const copy=structuredClone(state.sessions);copy[0].exercises[0].sets[1].reps=7;assert.equal(recommend(r.days[0].exercises[0],copy).kind,'maintain');copy[0].exercises[0].sets.forEach(s=>s.rir=0);assert.equal(recommend(r.days[0].exercises[0],copy).kind,'reduce');
state=reduce(state,{type:'start'});active=state.sessions.find(s=>s.status==='active');assert.equal(active.dayName,'Día B');state=reduce(state,{type:'restart',id:active.id});assert.equal(state.sessions.filter(s=>s.status==='active').length,1);assert.equal(state.sessions.find(s=>s.id===active.id).status,'cancelled');state=reduce(state,{type:'cancel',id:state.sessions.find(s=>s.status==='active').id});state=reduce(state,{type:'deleteRoutine',id:r.id});assert.equal(state.sessions[0].routineName,'Rutina de prueba');assert.equal(state.sessions[0].exercises[0].sets.length,3);
assert.throws(()=>reduce(state,{type:'measure',measurement:{id:uid(),date:'2026-09-16'}}));state=reduce(state,{type:'measure',measurement:{id:uid(),date:'2026-09-16',weight:73,waist:90}});assert.equal(state.measurements[0].weight,73);
assert.throws(()=>reduce(state,{type:'saveRoutine',routine:{...state.routines[0],days:[]}}));console.log('PASS: rutinas, activación única, duplicación, series, recuperación, temporizador, historial, siguiente día, progresión, PR, reinicio, cancelación, medidas y validación.');
