// Integration scenarios use the real repository's prepared SQL against SQLite.
import './run.mjs';
import {database,load,save,Conflict} from './repository.mjs';
import assert from 'node:assert/strict';
import path from 'node:path';
const dir=path.resolve('.sites-runtime/tests');
const {reduce}=await import(`${dir}/actions.js`);
const {sessionProgress,performedSets,workingSets,normalizeState}=await import(`${dir}/sets.js`);
const {recommend,records,volume}=await import(`${dir}/progression.js`);
let count=0;
const check=(name,fn)=>{fn();count++;console.log('PASS: '+name);};
async function act(user,state,action){const next=reduce(state,action);await save(user,state,next);return load(user);}
function context(state){const session=state.sessions.find(s=>s.status==='active');return {session,exercise:session.exercises[0]};}
async function setup(user,n){let s=await load(user);const r=structuredClone(s.routines[0]);r.days=[r.days[0]];r.days[0].exercises=[r.days[0].exercises[0]];Object.assign(r.days[0].exercises[0],{targetSets:n,rirMin:1,rirMax:2,min:5,max:8});s=await act(user,s,{type:'saveRoutine',routine:r});return act(user,s,{type:'start'});}
async function record(user,s,id,values={}){const {session,exercise}=context(s);return act(user,s,{type:'saveSet',sessionId:session.id,exerciseId:exercise.id,set:{id,weight:80,reps:8,rir:2,savedAt:new Date().toISOString(),...values}});}
for(const n of [1,3,5]){const user='series-'+n;let s=await setup(user,n);check(`${n} series: configuración y generación dinámica`,()=>{assert.equal(context(s).exercise.sets.length,n);assert.equal(sessionProgress(context(s).session).target,n);});for(const set of context(s).exercise.sets)s=await record(user,s,set.id);const {session,exercise}=context(s);check(`${n} series: 100% y finalización`,()=>assert.equal(sessionProgress(session).percent,100));s=await act(user,s,{type:'finish',id:session.id});check(`${n} series: aumento con todas las programadas`,()=>assert.equal(recommend(exercise.config,s.sessions).kind,'increase'));}
let user='extras',s=await setup(user,3),ctx=context(s);const original=JSON.stringify(s.routines),extra=crypto.randomUUID();s=await act(user,s,{type:'addSet',sessionId:ctx.session.id,exerciseId:ctx.exercise.id,id:extra,setType:'additional'});
check('añadir antes de completar, persistir y reabrir',()=>{assert.equal(context(s).exercise.sets.at(-1).id,extra);assert.equal(context(s).exercise.sets.at(-1).status,'pending');assert.equal(sessionProgress(context(s).session).target,3);assert.equal(JSON.stringify(s.routines),original);});
for(const set of context(s).exercise.sets.filter(s=>s.type==='programmed'))s=await record(user,s,set.id);
s=await record(user,s,extra,{reps:6,rir:0});
check('extra al fallo no altera cumplimiento',()=>{assert.equal(sessionProgress(context(s).session).percent,100);assert.equal(sessionProgress(context(s).session).additional,1);});
const extra2=crypto.randomUUID();ctx=context(s);s=await act(user,s,{type:'addSet',sessionId:ctx.session.id,exerciseId:ctx.exercise.id,id:extra2,setType:'additional'});s=await act(user,s,{type:'removeSet',sessionId:ctx.session.id,exerciseId:ctx.exercise.id,setId:extra2});
check('añadir después de completar y eliminar pendiente',()=>{assert.equal(context(s).exercise.sets.find(t=>t.id===extra2).status,'removed');assert.equal(sessionProgress(context(s).session).percent,100);});
const rest=context(s).session.restUntil;s=await record(user,s,extra,{weight:81,reps:7,rir:1});check('editar carga, reps y RIR sin reiniciar descanso',()=>{const edited=context(s).exercise.sets.find(t=>t.id===extra);assert.equal(edited.weight,81);assert.equal(edited.reps,7);assert.equal(edited.rir,1);assert.equal(context(s).session.restUntil,rest);});
s=await record(user,s,extra,{weight:80,reps:6,rir:0});ctx=context(s);s=await act(user,s,{type:'finish',id:ctx.session.id});check('finalizar con más series e historial adicional',()=>{assert.equal(performedSets(s.sessions[0].exercises[0].sets).length,4);assert.equal(s.sessions[0].exercises[0].sets.find(t=>t.id===extra).type,'additional');assert.equal(recommend(ctx.exercise.config,s.sessions).kind,'increase');assert.equal(JSON.stringify(s.routines).replace(/"nextDay":\d+/g,''),original.replace(/"nextDay":\d+/g,''));});
user='delete';s=await setup(user,3);ctx=context(s);const first=ctx.exercise.sets[0].id,second=ctx.exercise.sets[1].id;s=await record(user,s,first);ctx=context(s);check('confirmación obligatoria para eliminar realizada',()=>assert.throws(()=>reduce(s,{type:'removeSet',sessionId:ctx.session.id,exerciseId:ctx.exercise.id,setId:first}),/Confirma/));s=await act(user,s,{type:'removeSet',sessionId:ctx.session.id,exerciseId:ctx.exercise.id,setId:first,confirmed:true});s=await act(user,s,{type:'removeSet',sessionId:ctx.session.id,exerciseId:ctx.exercise.id,setId:second});
check('eliminar realizada y programada pendiente conserva objetivo',()=>{assert.equal(sessionProgress(context(s).session).target,3);assert.equal(sessionProgress(context(s).session).done,0);assert.equal(performedSets(context(s).exercise.sets).length,0);});
s=await record(user,s,context(s).exercise.sets[2].id);ctx=context(s);s=await act(user,s,{type:'finish',id:ctx.session.id});check('finalizar con menos series sin falsa progresión',()=>{assert.equal(sessionProgress(s.sessions[0]).done,1);assert.equal(recommend(ctx.exercise.config,s.sessions).kind,'maintain');assert.equal(performedSets(s.sessions[0].exercises[0].sets).length,1);});
user='warmup';s=await setup(user,1);ctx=context(s);const warm=crypto.randomUUID();s=await act(user,s,{type:'addSet',sessionId:ctx.session.id,exerciseId:ctx.exercise.id,id:warm,setType:'warmup'});s=await record(user,s,warm,{weight:500,reps:30,rir:0});check('calentamiento no permite finalizar sin trabajo',()=>assert.throws(()=>reduce(s,{type:'finish',id:ctx.session.id})));s=await record(user,s,ctx.exercise.sets[0].id);ctx=context(s);s=await act(user,s,{type:'finish',id:ctx.session.id});check('calentamientos excluidos de volumen, PR y progresión',()=>{assert.equal(volume(s.sessions[0].exercises[0].sets),640);assert.equal(records(s.sessions)[0].weight,80);assert.equal(recommend(ctx.exercise.config,s.sessions).kind,'increase');assert.equal(sessionProgress(s.sessions[0]).performed,1);});
user='legacy';s=await setup(user,3);ctx=context(s);s=await record(user,s,ctx.exercise.sets[0].id,{weight:57.5,reps:7,rir:3});
// Convert a private test account back to the exact original JSON model.
for(const row of database.prepare('SELECT id,data FROM routine_exercises WHERE user_id=?').all(user)){const d=JSON.parse(row.data);d.sets=d.targetSets;delete d.targetSets;database.prepare('UPDATE routine_exercises SET data=? WHERE user_id=? AND id=?').run(JSON.stringify(d),user,row.id);}
for(const row of database.prepare('SELECT id,data FROM exercise_sessions WHERE user_id=?').all(user)){const d=JSON.parse(row.data);d.config.sets=d.config.targetSets;delete d.config.targetSets;delete d.setsVersion;database.prepare('UPDATE exercise_sessions SET data=? WHERE user_id=? AND id=?').run(JSON.stringify(d),user,row.id);}
for(const row of database.prepare('SELECT id,data FROM sets WHERE user_id=?').all(user)){const d=JSON.parse(row.data);if(d.status==='pending')database.prepare('DELETE FROM sets WHERE user_id=? AND id=?').run(user,row.id);else{delete d.type;delete d.status;database.prepare('UPDATE sets SET data=? WHERE user_id=? AND id=?').run(JSON.stringify(d),user,row.id);}}
s=await load(user);check('compatibilidad de sesión antigua sin perder valores ni IDs',()=>{const e=context(s).exercise;assert.equal(e.sets.length,3);assert.equal(e.sets[0].id,ctx.exercise.sets[0].id);assert.equal(e.sets[0].weight,57.5);assert.equal(e.sets[0].rir,3);assert.deepEqual(normalizeState(s),s);});
ctx=context(s);const pending=ctx.exercise.sets[1].id;s=await act(user,s,{type:'removeSet',sessionId:ctx.session.id,exerciseId:ctx.exercise.id,setId:pending});s=await load(user);check('migración atómica: una eliminada no reaparece al recargar',()=>{assert.equal(context(s).exercise.sets.find(t=>t.id===pending).status,'removed');assert.equal(context(s).exercise.sets.length,3);assert.equal(context(s).exercise.sets[0].weight,57.5);});
const old=s;ctx=context(s);s=await act(user,s,{type:'addSet',sessionId:ctx.session.id,exerciseId:ctx.exercise.id,id:crypto.randomUUID(),setType:'additional'});await assert.rejects(()=>save(user,old,reduce(old,{type:'cancel',id:ctx.session.id})),Conflict);check('conflicto de dispositivos no borra serie adicional',()=>assert.equal(context(s).exercise.sets.length,4));
// Routine edits during a workout only affect the next workout.
const routine=structuredClone(s.routines[0]);routine.days[0].exercises[0].targetSets=5;s=await act(user,s,{type:'saveRoutine',routine});check('editar rutina no modifica sesión activa',()=>assert.equal(context(s).exercise.config.targetSets,3));s=await act(user,s,{type:'finish',id:ctx.session.id});s=await act(user,s,{type:'start'});check('siguiente sesión refleja nueva plantilla',()=>assert.equal(context(s).exercise.sets.length,5));
console.log(`PASS: ${count} escenarios de series con SQLite y recarga real del repositorio.`);
