'use client';
import { useState } from 'react';
import { Plus, TrendingUp, Dumbbell, Clock } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { uid, type AppState, type BodyMeasurement, type WorkoutSession } from '@/lib/domain/model';
import { performedSets, workingSets, setTypeLabel, sessionProgress } from '@/lib/domain/sets';
import { epley, records, volume } from '@/lib/domain/progression';
import { Field, Choice, Nothing, Trend, dateLabel, displayWeight, kg } from './shared';
import type { Send } from './routines';
const dimensions = [['weight', 'Peso', 'kg'], ['waist', 'Cintura', 'cm'], ['chest', 'Pecho', 'cm'], ['arm', 'Brazo', 'cm'], ['thigh', 'Muslo', 'cm'], ['neck', 'Cuello', 'cm'], ['fat', 'Grasa', '%']] as const;
export function History({ state }: {
    state: AppState;
}) { const [detail, setDetail] = useState<WorkoutSession | null>(null), sessions = [...state.sessions].filter(s => s.status !== 'active').reverse(); return <><div className="section-heading"><h2>{sessions.length} entrenamientos</h2><span className="muted">Tu historial completo</span></div>{sessions.length ? <div className="history-list">{sessions.map(s => <button className="panel history-row" key={s.id} onClick={() => setDetail(s)}><div className="history-date"><strong>{new Date(s.startedAt).getDate()}</strong><span>{new Date(s.startedAt).toLocaleDateString('es-ES', { month: 'short' })}</span></div><div className="history-name"><h3>{s.dayName} <span className="pill">{s.status === 'cancelled' ? 'Cancelada' : 'Completada'}</span></h3><p>{s.routineName}</p></div><div><strong>{sessionProgress(s).performed} series</strong><p>{Math.round((new Date(s.finishedAt!).getTime() - new Date(s.startedAt).getTime()) / 60000)} min</p></div></button>)}</div> : <Nothing title="Todavía no hay entrenamientos" description="Tu primera sesión será el punto de partida. La rutina Fuerza Base A/B está preparada."/>}<Dialog open={!!detail} onOpenChange={o => { if (!o)
    setDetail(null); }}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{detail?.dayName} · {detail?.routineName}</DialogTitle><DialogDescription>{detail && dateLabel(detail.startedAt, state.settings)} · {detail?.status === 'cancelled' ? 'Sesión cancelada' : 'Sesión completada'}</DialogDescription></DialogHeader>{detail && <div className="editor-body">{detail.exercises.map(e => <section key={e.id}><h3>{e.config.name}</h3><Table><TableHeader><TableRow><TableHead>Serie</TableHead><TableHead>{state.settings.unit}</TableHead><TableHead>Reps</TableHead>{state.settings.showRir && <TableHead>RIR</TableHead>}</TableRow></TableHeader><TableBody>{performedSets(e.sets).map((s, i) => <TableRow key={s.id}><TableCell>{i + 1}{s.type !== 'programmed' && <span className="pill ml-2">{setTypeLabel(s.type)}</span>}</TableCell><TableCell>{displayWeight(s.weight, state.settings.unit)}</TableCell><TableCell>{s.reps}</TableCell>{state.settings.showRir && <TableCell>{s.rir}</TableCell>}</TableRow>)}</TableBody></Table>{!performedSets(e.sets).length && <p className="muted">Sin series registradas.</p>}</section>)}</div>}</DialogContent></Dialog></>; }
export default function PhysicalProgress({ state, send, busy }: {
    state: AppState;
    send: Send;
    busy: boolean;
}) {
    const [metric, setMetric] = useState('weight'), [exerciseId, setExerciseId] = useState(state.exercises[0].id), [liftMetric, setLiftMetric] = useState('e1rm'), [draft, setDraft] = useState<BodyMeasurement | null>(null);
    const unit = state.settings.unit, dimension = dimensions.find(d => d[0] === metric)!, data = state.measurements.filter(m => typeof m[metric as keyof BodyMeasurement] === 'number').map(m => ({ date: dateLabel(m.date, state.settings), value: metric === 'weight' ? displayWeight(m.weight!, unit) : Number(m[metric as keyof BodyMeasurement]) }));
    const exercise = state.exercises.find(e => e.id === exerciseId), pr = records(state.sessions).find(r => r.exerciseId === exerciseId), history = state.sessions.filter(s => s.status === 'complete').sort((a, b) => (a.finishedAt ?? '').localeCompare(b.finishedAt ?? '')).map(s => ({ session: s, sets: s.exercises.filter(e => e.config.exerciseId === exerciseId).flatMap(e => workingSets(e.sets)) })).filter(x => x.sets.length);
    const liftData = history.map(({ session, sets }) => ({ date: dateLabel(session.startedAt, state.settings), value: liftMetric === 'volume' ? displayWeight(volume(sets), unit) : liftMetric === 'reps' ? Math.max(...sets.map(s => s.reps)) : displayWeight(Math.max(...sets.map(s => liftMetric === 'weight' ? s.weight : epley(s.weight, s.reps))), unit) }));
    return <><Tabs defaultValue="body"><TabsList><TabsTrigger value="body">Progreso físico</TabsTrigger><TabsTrigger value="strength">Fuerza y récords</TabsTrigger></TabsList><TabsContent value="body"><div className="section-heading"><h2>Un registro, una perspectiva</h2><Button onClick={() => setDraft({ id: uid(), date: new Date().toLocaleDateString('en-CA') })}><Plus /> Añadir registro</Button></div><article className="panel"><div className="chart-header"><div><span className="eyebrow">{dimension[1]}</span><h2 className="metric-number">{data.at(-1)?.value ?? '—'} <small>{metric === 'weight' ? unit : dimension[2]}</small></h2></div><div className="chart-select"><Choice value={metric} onChange={setMetric} label="Medida del gráfico" options={dimensions.map(d => ({ value: d[0], label: d[1] }))}/></div></div><Trend data={data} unit={metric === 'weight' ? unit : dimension[2]}/></article><div className="section-heading"><h2>Registros</h2><span className="muted">Toca un registro para editarlo</span></div>{state.measurements.length ? <div className="measurement-grid">{[...state.measurements].reverse().map(m => <button key={m.id} className="panel measurement-card" onClick={() => setDraft({ ...m })}><span className="eyebrow">{dateLabel(m.date, state.settings)}</span><h3>{m.weight ? displayWeight(m.weight, unit) + ' ' + unit : 'Medidas corporales'}</h3><p>{dimensions.filter(([k]) => k !== 'weight' && m[k] !== undefined).map(([k, label, u]) => `${label}: ${m[k]} ${u}`).join(' · ') || 'Sin perímetros registrados'}</p></button>)}</div> : <Nothing title="Sin medidas todavía" description="Registra tu peso y los perímetros que quieras seguir."/>}</TabsContent><TabsContent value="strength"><div className="section-heading"><h2>Ejercicio a ejercicio</h2></div><div className="two-columns"><Choice label="Ejercicio" value={exerciseId} onChange={v => { setExerciseId(v); if (state.exercises.find(e => e.id === v)?.type === 'bodyweight')
        setLiftMetric('reps'); }} options={state.exercises.map(e => ({ value: e.id, label: e.name }))}/><Choice label="Métrica" value={liftMetric} onChange={setLiftMetric} options={[{ value: 'weight', label: exercise?.type === 'bodyweight' ? 'Lastre máximo' : 'Carga máxima' }, { value: 'reps', label: 'Máximas repeticiones' }, { value: 'volume', label: 'Volumen externo' }, ...(exercise?.type === 'bodyweight' ? [] : [{ value: 'e1rm', label: '1RM estimado · Epley' }])]}/></div><div className="stats-grid three"><div className="panel stat"><span>Mayor carga</span><strong>{pr ? displayWeight(pr.weight, unit) : '—'}<small> {unit}</small></strong></div><div className="panel stat"><span>1RM estimado</span><strong>{pr && exercise?.type !== 'bodyweight' ? displayWeight(pr.e1rm, unit).toFixed(1) : '—'}<small> {unit}</small></strong></div><div className="panel stat"><span>Mejor volumen</span><strong>{pr ? displayWeight(pr.volume, unit).toLocaleString('es-ES') : '—'}<small> {unit}</small></strong></div></div><article className="panel"><h3>{exercise?.name}</h3><Trend data={liftData} unit={liftMetric === 'reps' ? 'reps' : unit}/><p className="hint">El e1RM es una estimación con la fórmula de Epley, no un máximo probado. El volumen suma carga externa × repeticiones; no incluye el peso corporal.</p></article><div className="section-heading"><h2>Mejores repeticiones por carga</h2></div>{pr ? <div className="day-pills">{Object.entries(pr.repsByWeight).sort((a, b) => Number(b[0]) - Number(a[0])).map(([w, r]) => <span key={w}>{displayWeight(Number(w), unit)} {unit} × {r}</span>)}</div> : <Nothing title="Tus récords aparecerán aquí" description="Se calculan a partir de las sesiones completadas."/>}<div className="section-heading"><h2>Últimos registros</h2></div>{history.slice(-10).reverse().map(({ session, sets }) => <div className="panel lift-history" key={session.id}><strong>{dateLabel(session.startedAt, state.settings)}</strong><p>{sets.map(s => `${displayWeight(s.weight, unit)} ${unit} × ${s.reps}${state.settings.showRir ? ' @' + s.rir : ''}${s.type === 'additional' ? ' · Serie adicional' : ''}`).join(' · ')}</p></div>)}</TabsContent></Tabs><Dialog open={!!draft} onOpenChange={o => { if (!o)
        setDraft(null); }}><DialogContent><DialogHeader><DialogTitle>Registro físico</DialogTitle><DialogDescription>Todos los campos son opcionales. Introduce al menos una medida.</DialogDescription></DialogHeader>{draft && <div className="form-stack"><Field label="Fecha" type="date" value={draft.date} onChange={v => setDraft({ ...draft, date: v })}/><div className="form-grid">{dimensions.map(([key, label, u]) => <Field key={key} label={label + ' (' + (key === 'weight' ? unit : u) + ')'} type="number" step={.1} value={draft[key] === undefined ? '' : key === 'weight' ? displayWeight(draft[key]!, unit) : draft[key]!} onChange={v => setDraft({ ...draft, [key]: v === '' ? undefined : key === 'weight' ? kg(Number(v), unit) : Number(v) })}/>)}</div><Button disabled={busy} onClick={async () => { if (await send({ type: 'measure', measurement: draft }))
        setDraft(null); }}>Guardar registro</Button></div>}</DialogContent></Dialog></>;
}
