'use client';
import { useState } from 'react';
import { Plus, ArrowUp, ArrowDown, Trash2, Copy, Archive, Check, BookOpen, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { uid, config, type AppState, type Routine, type Exercise } from '@/lib/domain/model';
import type { Action } from '@/lib/domain/actions';
import { Field, Choice, Nothing, dateLabel, displayWeight, kg } from './shared';
export type Send = (action: Action) => Promise<boolean>;
export default function Routines({ state, send, busy, confirm }: {
    state: AppState;
    send: Send;
    busy: boolean;
    confirm: (title: string, description: string, run: () => void) => void;
}) {
    const [editing, setEditing] = useState<Routine | null>(null), [ex, setEx] = useState<Exercise | null>(null);
    const save = async () => { if (editing && await send({ type: 'saveRoutine', routine: editing }))
        setEditing(null); };
    const patch = (fn: (r: Routine) => void) => setEditing(r => { if (!r)
        return r; const n = structuredClone(r); fn(n); return n; });
    return <><Tabs defaultValue="routines"><div className="section-toolbar"><TabsList><TabsTrigger value="routines">Mis rutinas</TabsTrigger><TabsTrigger value="library">Biblioteca · {state.exercises.length}</TabsTrigger></TabsList><Button onClick={() => setEditing({ id: uid(), name: 'Nueva rutina', description: '', createdAt: new Date().toISOString(), status: 'draft', nextDay: 0, days: [{ id: uid(), name: 'Día A', exercises: [] }] })}><Plus /> Nueva rutina</Button></div><TabsContent value="routines"><div className="routine-grid">{state.routines.map(r => <article className={'panel routine-card ' + (r.status === 'active' ? 'is-active' : '')} key={r.id}><div className="spread"><span className="eyebrow">{r.days.length} DÍAS · {r.days.reduce((n, d) => n + d.exercises.length, 0)} EJERCICIOS</span><span className={'pill ' + r.status}>{r.status === 'active' ? 'Activa' : r.status === 'archived' ? 'Archivada' : 'Borrador'}</span></div><h2>{r.name}</h2><p>{r.description || 'Tu próxima etapa de entrenamiento.'}</p><div className="day-pills">{r.days.map(d => <span key={d.id}>{d.name}</span>)}</div><small>Creada el {dateLabel(r.createdAt, state.settings)}</small><div className="card-actions"><Button variant="secondary" onClick={() => setEditing(structuredClone(r))}>Abrir y editar <ChevronRight /></Button>{r.status !== 'active' && <Button variant="outline" disabled={busy} onClick={() => send({ type: 'activate', id: r.id })}><Check /> Activar</Button>}<Button variant="ghost" aria-label={'Duplicar ' + r.name} disabled={busy} onClick={() => send({ type: 'duplicate', id: r.id })}><Copy /></Button><Button variant="ghost" aria-label={'Archivar ' + r.name} disabled={busy} onClick={() => send({ type: 'archive', id: r.id })}><Archive /></Button><Button variant="ghost" aria-label={'Eliminar ' + r.name} disabled={busy} onClick={() => confirm('¿Eliminar esta rutina?', 'El historial de entrenamientos se conservará.', () => { void send({ type: 'deleteRoutine', id: r.id }); })}><Trash2 /></Button></div></article>)}</div>{!state.routines.length && <Nothing title="Tu primera rutina" description="Crea una rutina y organiza tus días de entrenamiento."/>}</TabsContent><TabsContent value="library"><div className="section-heading"><h2>Ejercicios</h2><Button variant="outline" onClick={() => setEx({ id: uid(), name: '', group: 'General', equipment: 'Barra', notes: '', type: 'loaded' })}><Plus /> Crear ejercicio</Button></div><div className="exercise-library">{state.exercises.map(e => <button className="panel library-item" key={e.id} onClick={() => setEx({ ...e })}><div className="exercise-icon"><BookOpen size={19}/></div><div><strong>{e.name}</strong><p>{e.group} · {e.equipment}</p></div><ChevronRight size={18}/></button>)}</div></TabsContent></Tabs>
    <Dialog open={!!editing} onOpenChange={open => { if (!open)
        setEditing(null); }}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>Editar rutina</DialogTitle><DialogDescription>Los cambios se aplican a futuras sesiones. Tu historial se conserva.</DialogDescription></DialogHeader>{editing && <div className="editor-body"><Field label="Nombre de la rutina" value={editing.name} onChange={v => patch(r => { r.name = v; })}/><label className="field"><span>Descripción</span><Textarea value={editing.description} onChange={e => patch(r => { r.description = e.target.value; })}/></label>{editing.days.map((day, di) => <section className="day-editor" key={day.id}><div className="spread"><Field label="Nombre del día" value={day.name} onChange={v => patch(r => { r.days[di].name = v; })}/><Button variant="ghost" aria-label="Eliminar día" disabled={editing.days.length === 1} onClick={() => patch(r => { r.days.splice(di, 1); })}><Trash2 /></Button></div>{day.exercises.map((e, ei) => <div className="exercise-editor" key={e.id}><div className="spread"><strong>{ei + 1}. {e.name}</strong><div className="inline-actions"><Button variant="ghost" aria-label="Subir ejercicio" disabled={ei === 0} onClick={() => patch(r => { const a = r.days[di].exercises; [a[ei - 1], a[ei]] = [a[ei], a[ei - 1]]; })}><ArrowUp /></Button><Button variant="ghost" aria-label="Bajar ejercicio" disabled={ei === day.exercises.length - 1} onClick={() => patch(r => { const a = r.days[di].exercises; [a[ei + 1], a[ei]] = [a[ei], a[ei + 1]]; })}><ArrowDown /></Button><Button variant="ghost" aria-label="Quitar ejercicio" onClick={() => patch(r => { r.days[di].exercises.splice(ei, 1); })}><Trash2 /></Button></div></div><div className="form-grid"><Field label="Nombre" value={e.name} onChange={v => patch(r => { r.days[di].exercises[ei].name = v; })}/><Field label="Grupo muscular" value={e.group} onChange={v => patch(r => { r.days[di].exercises[ei].group = v; })}/><label className="field"><span>Tipo</span><Choice label="Tipo de ejercicio" value={e.type} onChange={v => patch(r => { r.days[di].exercises[ei].type = v as Exercise['type']; })} options={[{ value: 'loaded', label: 'Carga externa' }, { value: 'bodyweight', label: 'Peso corporal / lastre' }]}/></label>{([['sets', 'Series'], ['min', 'Reps mín.'], ['max', 'Reps máx.'], ['rirMin', 'RIR mín.'], ['rirMax', 'RIR máx.'], ['increment', 'Incremento (' + state.settings.unit + ')'], ['rest', 'Descanso (seg.)']] as const).map(([key, label]) => <Field key={key} label={label} type="number" step={key === 'increment' ? .01 : 1} value={key === 'increment' ? displayWeight(e[key], state.settings.unit) : e[key]} onChange={v => patch(r => { r.days[di].exercises[ei][key] = key === 'increment' ? kg(Number(v), state.settings.unit) : Number(v); })}/>)}</div><Field label="Notas" value={e.notes} onChange={v => patch(r => { r.days[di].exercises[ei].notes = v; })}/></div>)}<Choice label="Añadir ejercicio" value="add" onChange={id => { const e = state.exercises.find(e => e.id === id); if (e)
        patch(r => { r.days[di].exercises.push(config(e, state.settings.increment)); }); }} options={[{ value: 'add', label: '+ Añadir ejercicio de la biblioteca' }, ...state.exercises.map(e => ({ value: e.id, label: e.name }))]}/></section>)}<Button variant="outline" onClick={() => patch(r => { r.days.push({ id: uid(), name: 'Día ' + (r.days.length + 1), exercises: [] }); })}><Plus /> Añadir día</Button><div className="editor-footer"><Button variant="ghost" onClick={() => setEditing(null)}>Cerrar sin guardar</Button><Button disabled={busy} onClick={save}>{busy ? 'Guardando…' : 'Guardar rutina'}</Button></div></div>}</DialogContent></Dialog>
    <Dialog open={!!ex} onOpenChange={o => { if (!o)
        setEx(null); }}><DialogContent><DialogHeader><DialogTitle>{ex?.name || 'Nuevo ejercicio'}</DialogTitle><DialogDescription>La biblioteca es tuya. Los ejercicios ya añadidos a rutinas conservan su configuración.</DialogDescription></DialogHeader>{ex && <div className="form-stack">{(['name', 'group', 'equipment', 'notes'] as const).map((k, i) => <Field key={k} label={['Nombre', 'Grupo muscular', 'Equipamiento', 'Notas'][i]} value={ex[k]} onChange={v => setEx({ ...ex, [k]: v })}/>)}<Choice label="Tipo" value={ex.type} onChange={v => setEx({ ...ex, type: v as Exercise['type'] })} options={[{ value: 'loaded', label: 'Carga externa' }, { value: 'bodyweight', label: 'Peso corporal / lastre' }]}/><Button disabled={busy} onClick={async () => { if (await send({ type: 'saveExercise', exercise: ex }))
        setEx(null); }}>Guardar ejercicio</Button></div>}</DialogContent></Dialog></>;
}
