'use client';
import { useState, useEffect } from 'react';
import { Check, Play, Pause, SkipForward, Plus, Minus, ChevronLeft, ChevronRight, Timer, RotateCcw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import { Table, TableHeader, TableHead, TableRow, TableBody, TableCell } from '@/components/ui/table';
import { uid, type AppState, type WorkoutSession } from '@/lib/domain/model';
import { previous, recommend } from '@/lib/domain/progression';
import { displayWeight, kg } from './shared';
import type { Send } from './routines';
export default function Workout({ state, session, send, busy, close, confirm }: {
    state: AppState;
    session: WorkoutSession;
    send: Send;
    busy: boolean;
    close: () => void;
    confirm: (title: string, description: string, run: () => void) => void;
}) {
    const [index, setIndex] = useState(() => Math.max(0, session.exercises.findIndex(e => e.sets.length < e.config.sets))), [edit, setEdit] = useState<number | null>(null), [weight, setWeight] = useState('0'), [reps, setReps] = useState('5'), [rir, setRir] = useState(2), [now, setNow] = useState(Date.now());
    const ex = session.exercises[index], c = ex.config, rec = recommend(c, state.sessions), last = previous(state.sessions, c.exerciseId), unit = state.settings.unit;
    useEffect(() => { const t = setInterval(() => setNow(Date.now()), 500); return () => clearInterval(t); }, []);
    useEffect(() => { const row = edit === null ? null : ex.sets[edit], prior = ex.sets.at(-1); setWeight(String(displayWeight(row?.weight ?? prior?.weight ?? rec.weight, unit))); setReps(String(row?.reps ?? rec.reps[ex.sets.length] ?? c.min)); setRir(row?.rir ?? c.rirMin); }, [ex.id, ex.sets.length, edit, unit]);
    const total = session.exercises.reduce((n, e) => n + e.config.sets, 0), done = session.exercises.reduce((n, e) => n + e.sets.length, 0), seconds = session.restRemaining ?? Math.max(0, Math.ceil(((session.restUntil ?? 0) - now) / 1000));
    const save = async () => { const ok = await send({ type: 'saveSet', sessionId: session.id, exerciseId: ex.id, set: { id: edit === null ? uid() : ex.sets[edit].id, weight: kg(Number(weight), unit), reps: Number(reps), rir, savedAt: new Date().toISOString() } }); if (ok) {
        setEdit(null);
        if (edit === null && ex.sets.length + 1 >= c.sets && index < session.exercises.length - 1)
            setIndex(index + 1);
    } };
    return <div className="workout-wrap"><div className="spread"><Button variant="ghost" onClick={close}><ChevronLeft /> Inicio</Button><span className="pill active">Sesión en curso</span></div><div className="workout-title"><div><span className="eyebrow">{session.routineName}</span><h1>{session.dayName}</h1></div><span className="elapsed tabular">{Math.floor((now - new Date(session.startedAt).getTime()) / 60000)}<small> min</small></span></div><div className="spread muted"><span>{done} de {total} series</span><span>Ejercicio {index + 1} / {session.exercises.length}</span></div><Progress value={done / total * 100} className="my-3"/><div className="exercise-stepper">{session.exercises.map((e, i) => <button key={e.id} className={index === i ? 'selected' : ''} onClick={() => { setIndex(i); setEdit(null); }}>{e.sets.length === e.config.sets ? <Check size={14}/> : i + 1}<span>{e.config.name}</span></button>)}</div><article className="panel workout-panel"><span className="eyebrow">{c.group} · {c.sets} × {c.min}–{c.max} · RIR {c.rirMin}–{c.rirMax}</span><h2>{c.name}</h2>{c.notes && <p>{c.notes}</p>}<div className="previous"><span>Última sesión</span><strong>{last ? last.sets.map(s => `${displayWeight(s.weight, unit)} × ${s.reps} @${s.rir}`).join(' · ') : 'Sin registros todavía'}</strong></div><div className="recommendation"><div><span className="eyebrow">{rec.kind === 'increase' ? 'SUBIR CARGA' : rec.kind === 'reduce' ? 'AJUSTAR CARGA' : 'PRÓXIMA SERIE'}</span><p>{rec.reason}</p></div><strong>{rec.kind === 'start' ? '—' : displayWeight(rec.weight, unit)}<small> {unit}</small></strong></div>{c.type === 'bodyweight' && <p className="hint">Registra solo el lastre añadido. Sin lastre, introduce 0 {unit}. No se estima 1RM para este ejercicio.</p>}
    {ex.sets.length > 0 && <Table><TableHeader><TableRow><TableHead>Serie</TableHead><TableHead>{unit}</TableHead><TableHead>Reps</TableHead><TableHead>RIR</TableHead><TableHead /></TableRow></TableHeader><TableBody>{ex.sets.map((s, i) => <TableRow key={s.id}><TableCell><Check size={15} className="lime"/> {i + 1}</TableCell><TableCell>{displayWeight(s.weight, unit)}</TableCell><TableCell>{s.reps}</TableCell><TableCell>{s.rir}</TableCell><TableCell><Button variant="ghost" onClick={() => setEdit(i)}>Editar</Button></TableCell></TableRow>)}</TableBody></Table>}
    {(ex.sets.length < c.sets || edit !== null) ? <div className="set-entry"><div className="spread"><h3>{edit === null ? 'Serie ' + (ex.sets.length + 1) : 'Editar serie ' + (edit + 1)}</h3>{ex.sets.length > 0 && <Button variant="ghost" onClick={() => setWeight(String(displayWeight(ex.sets.at(-1)!.weight, unit)))}>Copiar peso anterior</Button>}</div><div className="entry-grid">{[{ label: c.type === 'bodyweight' ? 'Lastre (' + unit + ')' : 'Peso (' + unit + ')', value: weight, set: setWeight, step: displayWeight(c.increment, unit), min: 0 }, { label: 'Repeticiones', value: reps, set: setReps, step: 1, min: 1 }].map(field => <label className="number-field" key={field.label}><span>{field.label}</span><div><Button variant="secondary" aria-label={'Reducir ' + field.label} onClick={() => field.set(String(Math.max(field.min, Math.round((Number(field.value) - field.step) * 100) / 100)))}><Minus /></Button><Input type="number" min={field.min} step={field.label === 'Repeticiones' ? 1 : .01} inputMode="decimal" value={field.value} onChange={e => field.set(e.target.value)}/><Button variant="secondary" aria-label={'Aumentar ' + field.label} onClick={() => field.set(String(Math.round((Number(field.value) + field.step) * 100) / 100))}><Plus /></Button></div></label>)}</div><label className="field"><span>RIR · repeticiones que te quedaban</span><div className="rir-picker">{[0, 1, 2, 3, 4, 5].map(n => <Button variant={rir === n ? 'default' : 'secondary'} key={n} onClick={() => setRir(n)} aria-pressed={rir === n}>{n}</Button>)}</div></label><Button className="save-set" disabled={busy || weight === '' || reps === ''} onClick={save}><Check />{busy ? 'Guardando…' : edit === null ? 'Guardar serie' : 'Guardar cambios'}</Button>{edit !== null && <Button variant="ghost" onClick={() => setEdit(null)}>Cancelar edición</Button>}</div> : <div className="exercise-complete"><Check /><h3>Ejercicio completado</h3>{index < session.exercises.length - 1 && <Button onClick={() => setIndex(index + 1)}>Siguiente ejercicio <ChevronRight /></Button>}</div>}</article>
    {(seconds > 0 || session.restRemaining !== null) && <div className="rest-bar"><Timer /><div><small>DESCANSO</small><strong className="tabular">{Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, '0')}</strong></div><Button variant="ghost" aria-label={session.restRemaining !== null ? 'Reanudar descanso' : 'Pausar descanso'} disabled={busy} onClick={() => send({ type: 'timer', id: session.id, restUntil: session.restRemaining !== null ? Date.now() + seconds * 1000 : null, restRemaining: session.restRemaining !== null ? null : seconds })}>{session.restRemaining !== null ? <Play /> : <Pause />}</Button><Button variant="ghost" disabled={busy} onClick={() => send({ type: 'timer', id: session.id, restUntil: session.restRemaining === null ? Date.now() + (seconds + 30) * 1000 : null, restRemaining: session.restRemaining !== null ? seconds + 30 : null })}>+30 s</Button><Button variant="ghost" aria-label="Saltar descanso" disabled={busy} onClick={() => send({ type: 'timer', id: session.id, restUntil: null, restRemaining: null })}><SkipForward /></Button></div>}
    <div className="workout-footer"><Button variant="outline" disabled={busy} onClick={() => confirm('¿Reiniciar esta sesión?', 'La sesión anterior se conservará como cancelada y empezarás de cero.', async () => { await send({ type: 'restart', id: session.id }); })}><RotateCcw /> Reiniciar</Button><Button disabled={busy || done === 0} onClick={() => confirm('¿Finalizar entrenamiento?', done < total ? `Llevas ${done} de ${total} series. Se guardarán las realizadas y avanzarás al siguiente día.` : 'Todas las series están listas. Se guardará la sesión completa.', async () => { if (await send({ type: 'finish', id: session.id }))
        close(); })}>Finalizar <Check /></Button></div><Button className="cancel-session" variant="ghost" disabled={busy} onClick={() => confirm('¿Cancelar la sesión?', 'Las series guardadas se conservarán en el historial como sesión cancelada.', async () => { if (await send({ type: 'cancel', id: session.id }))
        close(); })}>Cancelar sesión</Button></div>;
}
